# Generated by Django 4.2.1 on 2025-08-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='company',
            name='charity_frequency',
            field=models.CharField(choices=[('monthly', 'Ежемесячно'), ('yearly', 'Ежегодно'), ('weekly_friday', 'По пятницам'), ('percent_revenue', 'Процент от выручки'), ('tooba_collections', 'На сборы в Tooba'), ('once', 'Разово')], max_length=50, verbose_name='Периодичность'),
        ),
    ]
