# Generated by Django 4.2.1 on 2025-08-23 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_logo_alter_company_charity_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Контактное лицо')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Сайт компании')),
                ('description', models.TextField(verbose_name='Описание компании')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('charity_description', models.TextField(verbose_name='Описание благотворительной деятельности')),
                ('charity_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма пожертвований')),
                ('charity_frequency', models.CharField(choices=[('monthly', 'Ежемесячно'), ('yearly', 'Ежегодно'), ('weekly_friday', 'По пятницам'), ('percent_revenue', 'Процент от выручки'), ('tooba_collections', 'На сборы в Tooba'), ('once', 'Разово')], max_length=50, verbose_name='Периодичность')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Заявка компании',
                'verbose_name_plural': 'Заявки компаний',
                'ordering': ['-created_at'],
            },
        ),
    ]
